# Name : Reem Hussein
# Netid: rhusse3
# CS account : rhussein
# CS342 Project 3

make all: AI.java Artifact.java Character.java CleanLineScanner.java DecisionMaker.java Direction.java Drop.java Game.java GameTester.java Get.java Go.java Halt.java Invalid.java Inventory.java KeyboardScanner.java Look.java Move.java NPC.java Place.java Player.java Quit.java UI.java Use.java
	javac *.java
clean:
	$(RM) *.class
